name: Deploy Selected Files to S3

on:
  workflow_dispatch:  # Allows you to run this workflow manually
  push:
    branches:
      - main
    paths:
      - ForntEnd/**  # Run the workflow when files in the FrontEnd directory are changed
    

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy Selected Files to S3
        run: |
          aws s3 cp FrontEnd s3://${{ secrets.S3_BUCKET_NAME }}

